// WASM model-viewer island — the DOM-side boundary for the `dam-viewer` wgpu component
// (tech-spec 09 §B.3, ADR 0009 §9). This is the seam a React wrapper builds on: it owns a `<canvas>`
// and this module's lifecycle (create on mount, `free()` on unmount), while the island owns pixels.
//
// The DOM owns the data and the chrome (tech-spec 09 §B.1/§B.3): fetch preview-mesh bytes over the
// file-03 API (`@/api/client`) and hand them across; camera controls are DOM and call `setCamera`.
// The island never does its own networking.
//
// The heavy `.wasm` (built by `cargo xtask wasm` → wasm-pack) is fetched **lazily** on first use, so
// the browse grid and Canvas2D audio waveform pay nothing for it — only opening a 3D asset pulls it
// in.

/** Live 3D viewer. Mirrors the `ModelViewer` wasm-bindgen export in `crates/3dam-viewer`. */
export interface ModelViewerHandle {
  /** Backend actually chosen: `"webgpu"` or `"webgl2"`. */
  readonly backend: string;
  /** Decode + display a server-produced `DMSH` preview blob (geometry + PBR materials + textures).
   *  Decoded server-side from any Assimp format and self-contained, so the DOM hands it straight in
   *  with no buffer/texture resolution. */
  loadPreviewMesh(bytes: Uint8Array): void;
  /** Orbit + zoom. `yaw`/`pitch` in radians; `zoom` multiplies the bounds-fit distance. */
  setCamera(yaw: number, pitch: number, zoom: number): void;
  /** Orbit, zoom, and view-plane pan (`panX`/`panY` are viewport fractions). */
  setCameraPose(
    yaw: number,
    pitch: number,
    zoom: number,
    panX: number,
    panY: number,
  ): void;
  /** Lighting mode (issue #65): 0 studio (3-light rig + hemi), 1 soft (shadowless fill), 2 flat/unlit. */
  setLighting(mode: number): void;
  /** Toggle the wireframe overlay — mesh edges instead of shaded surfaces (issue #65). */
  setWireframe(on: boolean): void;
  /** New canvas backing size in device pixels — call on container resize (CSS owns layout). */
  resize(width: number, height: number): void;
  /** Whether a model has loaded (vs the empty neutral background). */
  hasModel(): boolean;
  /** Effective 4×/2×/1× MSAA count selected for the active backend. */
  readonly antialiasingSamples: number;
  /** Source submesh draws before material batching. */
  readonly sourceDrawCount: number;
  /** Actual shaded draws after opaque/masked material batching. */
  readonly batchedDrawCount: number;
  /** Versioned browser/headless framing contract. */
  readonly framingVersion: number;
  /** Tear down the island: stops its render loop and releases the GPU device/surface. */
  free(): void;
}

/** Shape of the wasm-pack ES module (`web/src/wasm/dam_viewer.js`), typed locally. */
interface DamViewerModule {
  /** wasm-bindgen `init` — instantiates the `.wasm`; no-arg form fetches the sibling file. */
  default: () => Promise<unknown>;
  ModelViewer: { create(canvas: HTMLCanvasElement): Promise<ModelViewerHandle> };
}

let modulePromise: Promise<DamViewerModule> | null = null;

/**
 * Lazily import + instantiate the island module, once per page. The `@ts-ignore` is deliberate: the
 * generated pkg under `@/wasm/` is a build artifact (gitignored, produced by `cargo xtask wasm`), so
 * it may be absent when the rest of the app is type-checked. We type the module ourselves above.
 */
function loadModule(): Promise<DamViewerModule> {
  if (!modulePromise) {
    modulePromise = (async () => {
      // @ts-ignore — generated by `cargo xtask wasm` (wasm-pack); not present until built.
      const mod = (await import("@/wasm/dam_viewer.js")) as unknown as DamViewerModule;
      await mod.default();
      return mod;
    })();
  }
  return modulePromise;
}

/** Spin up a 3D viewer island bound to `canvas`. Rejects if neither WebGPU nor WebGL2 is available. */
export async function createModelViewer(
  canvas: HTMLCanvasElement,
): Promise<ModelViewerHandle> {
  const mod = await loadModule();
  return mod.ModelViewer.create(canvas);
}
