/// <reference types="vite/client" />

// Generated by `cargo xtask wasm`; declare its stable import path so a clean-tree typecheck does
// not depend on ignored build artifacts already being present.
declare module "@/wasm/dam_viewer.js";
